// Generado por tools/tokens_to_kotlin.py a partir de design/figma-tokens.json.
// Archivo de Figma: Solventa Design System (F8uIyyRnLbTfZ6zKPP9pCq).
// No editar a mano: volver a extraer de Figma y ejecutar el generador.

package com.solventa4bits.movil.ui.tema

import androidx.compose.ui.graphics.Color

// Esquema light
internal val primaryClaro = Color(0xFF006971)
internal val onPrimaryClaro = Color(0xFFFFFFFF)
internal val primaryContainerClaro = Color(0xFF9DF0FA)
internal val onPrimaryContainerClaro = Color(0xFF004F55)
internal val secondaryClaro = Color(0xFF4A6366)
internal val onSecondaryClaro = Color(0xFFFFFFFF)
internal val secondaryContainerClaro = Color(0xFFCDE7EB)
internal val onSecondaryContainerClaro = Color(0xFF4A4459)
internal val tertiaryClaro = Color(0xFF505E7D)
internal val onTertiaryClaro = Color(0xFFFFFFFF)
internal val tertiaryContainerClaro = Color(0xFFD8E2FF)
internal val onTertiaryContainerClaro = Color(0xFF394764)
internal val errorClaro = Color(0xFFBA1A1A)
internal val onErrorClaro = Color(0xFFFFFFFF)
internal val errorContainerClaro = Color(0xFFFFDAD6)
internal val onErrorContainerClaro = Color(0xFF93000A)
internal val backgroundClaro = Color(0xFFF5FAFB)
internal val onBackgroundClaro = Color(0xFF161D1D)
internal val surfaceClaro = Color(0xFFF5FAFB)
internal val onSurfaceClaro = Color(0xFF161D1D)
internal val surfaceVariantClaro = Color(0xFFDAE4E5)
internal val onSurfaceVariantClaro = Color(0xFF3F484A)
internal val outlineClaro = Color(0xFF6F797A)
internal val outlineVariantClaro = Color(0xFFBEC8C9)
internal val surfaceTintClaro = Color(0xFF006971)
internal val shadowClaro = Color(0xFF000000)
internal val scrimClaro = Color(0xFF000000)
internal val inverseSurfaceClaro = Color(0xFF2B3132)
internal val inverseOnSurfaceClaro = Color(0xFFECF2F2)
internal val inversePrimaryClaro = Color(0xFF81D3DD)
internal val primaryFixedClaro = Color(0xFF9DF0FA)
internal val onPrimaryFixedClaro = Color(0xFF002023)
internal val primaryFixedDimClaro = Color(0xFF81D3DD)
internal val onPrimaryFixedVariantClaro = Color(0xFF004F55)
internal val secondaryFixedClaro = Color(0xFFCDE7EB)
internal val onSecondaryFixedClaro = Color(0xFF051F22)
internal val secondaryFixedDimClaro = Color(0xFFB1CBCF)
internal val onSecondaryFixedVariantClaro = Color(0xFF324B4E)
internal val tertiaryFixedClaro = Color(0xFFD8E2FF)
internal val onTertiaryFixedClaro = Color(0xFF0B1B36)
internal val tertiaryFixedDimClaro = Color(0xFFB8C6EA)
internal val onTertiaryFixedVariantClaro = Color(0xFF394764)
internal val surfaceDimClaro = Color(0xFFD5DBDC)
internal val surfaceBrightClaro = Color(0xFFF5FAFB)
internal val surfaceContainerLowestClaro = Color(0xFFFFFFFF)
internal val surfaceContainerLowClaro = Color(0xFFEFF5F5)
internal val surfaceContainerClaro = Color(0xFFE9EFEF)
internal val surfaceContainerHighClaro = Color(0xFFE3E9EA)
internal val surfaceContainerHighestClaro = Color(0xFFDEE4E4)

// Esquema dark
internal val primaryOscuro = Color(0xFF81D3DD)
internal val onPrimaryOscuro = Color(0xFF00363B)
internal val primaryContainerOscuro = Color(0xFF004F55)
internal val onPrimaryContainerOscuro = Color(0xFF9DF0FA)
internal val secondaryOscuro = Color(0xFFB1CBCF)
internal val onSecondaryOscuro = Color(0xFF1C3437)
internal val secondaryContainerOscuro = Color(0xFF324B4E)
internal val onSecondaryContainerOscuro = Color(0xFFE8DEF8)
internal val tertiaryOscuro = Color(0xFFB8C6EA)
internal val onTertiaryOscuro = Color(0xFF22304C)
internal val tertiaryContainerOscuro = Color(0xFF394764)
internal val onTertiaryContainerOscuro = Color(0xFFD8E2FF)
internal val errorOscuro = Color(0xFFFFB4AB)
internal val onErrorOscuro = Color(0xFF690005)
internal val errorContainerOscuro = Color(0xFF93000A)
internal val onErrorContainerOscuro = Color(0xFFFFDAD6)
internal val backgroundOscuro = Color(0xFF0E1415)
internal val onBackgroundOscuro = Color(0xFFDEE4E4)
internal val surfaceOscuro = Color(0xFF0E1415)
internal val onSurfaceOscuro = Color(0xFFDEE4E4)
internal val surfaceVariantOscuro = Color(0xFF3F484A)
internal val onSurfaceVariantOscuro = Color(0xFFBEC8C9)
internal val outlineOscuro = Color(0xFF899294)
internal val outlineVariantOscuro = Color(0xFF3F484A)
internal val surfaceTintOscuro = Color(0xFF81D3DD)
internal val shadowOscuro = Color(0xFF000000)
internal val scrimOscuro = Color(0xFF000000)
internal val inverseSurfaceOscuro = Color(0xFFDEE4E4)
internal val inverseOnSurfaceOscuro = Color(0xFF2B3132)
internal val inversePrimaryOscuro = Color(0xFF006971)
internal val primaryFixedOscuro = Color(0xFF9DF0FA)
internal val onPrimaryFixedOscuro = Color(0xFF002023)
internal val primaryFixedDimOscuro = Color(0xFF81D3DD)
internal val onPrimaryFixedVariantOscuro = Color(0xFF004F55)
internal val secondaryFixedOscuro = Color(0xFFCDE7EB)
internal val onSecondaryFixedOscuro = Color(0xFF051F22)
internal val secondaryFixedDimOscuro = Color(0xFFB1CBCF)
internal val onSecondaryFixedVariantOscuro = Color(0xFF324B4E)
internal val tertiaryFixedOscuro = Color(0xFFD8E2FF)
internal val onTertiaryFixedOscuro = Color(0xFF0B1B36)
internal val tertiaryFixedDimOscuro = Color(0xFFB8C6EA)
internal val onTertiaryFixedVariantOscuro = Color(0xFF394764)
internal val surfaceDimOscuro = Color(0xFF0E1415)
internal val surfaceBrightOscuro = Color(0xFF343A3B)
internal val surfaceContainerLowestOscuro = Color(0xFF090F10)
internal val surfaceContainerLowOscuro = Color(0xFF161D1D)
internal val surfaceContainerOscuro = Color(0xFF1A2121)
internal val surfaceContainerHighOscuro = Color(0xFF252B2C)
internal val surfaceContainerHighestOscuro = Color(0xFF303637)

// Marca. El teal de acento y la tipografia del logo no son roles del
// sistema: pertenecen al logo y no a la interfaz operativa.
internal val AccentTeal = Color(0xFF00C8D7)
internal val BrandBlack = Color(0xFF000000)
internal val BrandWhite = Color(0xFFFFFFFF)
