// Generado por tools/tokens_to_kotlin.py a partir de design/figma-tokens.json.
// Archivo de Figma: Solventa Design System (F8uIyyRnLbTfZ6zKPP9pCq).
// No editar a mano: volver a extraer de Figma y ejecutar el generador.

package com.solventa4bits.movil.ui.tema

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

internal val EsquemaClaro = lightColorScheme(
    primary = primaryClaro,
    onPrimary = onPrimaryClaro,
    primaryContainer = primaryContainerClaro,
    onPrimaryContainer = onPrimaryContainerClaro,
    secondary = secondaryClaro,
    onSecondary = onSecondaryClaro,
    secondaryContainer = secondaryContainerClaro,
    onSecondaryContainer = onSecondaryContainerClaro,
    tertiary = tertiaryClaro,
    onTertiary = onTertiaryClaro,
    tertiaryContainer = tertiaryContainerClaro,
    onTertiaryContainer = onTertiaryContainerClaro,
    error = errorClaro,
    onError = onErrorClaro,
    errorContainer = errorContainerClaro,
    onErrorContainer = onErrorContainerClaro,
    background = backgroundClaro,
    onBackground = onBackgroundClaro,
    surface = surfaceClaro,
    onSurface = onSurfaceClaro,
    surfaceVariant = surfaceVariantClaro,
    onSurfaceVariant = onSurfaceVariantClaro,
    outline = outlineClaro,
    outlineVariant = outlineVariantClaro,
    scrim = scrimClaro,
    inverseSurface = inverseSurfaceClaro,
    inverseOnSurface = inverseOnSurfaceClaro,
    inversePrimary = inversePrimaryClaro,
    surfaceDim = surfaceDimClaro,
    surfaceBright = surfaceBrightClaro,
    surfaceContainerLowest = surfaceContainerLowestClaro,
    surfaceContainerLow = surfaceContainerLowClaro,
    surfaceContainer = surfaceContainerClaro,
    surfaceContainerHigh = surfaceContainerHighClaro,
    surfaceContainerHighest = surfaceContainerHighestClaro,
    surfaceTint = surfaceTintClaro,
)

internal val EsquemaOscuro = darkColorScheme(
    primary = primaryOscuro,
    onPrimary = onPrimaryOscuro,
    primaryContainer = primaryContainerOscuro,
    onPrimaryContainer = onPrimaryContainerOscuro,
    secondary = secondaryOscuro,
    onSecondary = onSecondaryOscuro,
    secondaryContainer = secondaryContainerOscuro,
    onSecondaryContainer = onSecondaryContainerOscuro,
    tertiary = tertiaryOscuro,
    onTertiary = onTertiaryOscuro,
    tertiaryContainer = tertiaryContainerOscuro,
    onTertiaryContainer = onTertiaryContainerOscuro,
    error = errorOscuro,
    onError = onErrorOscuro,
    errorContainer = errorContainerOscuro,
    onErrorContainer = onErrorContainerOscuro,
    background = backgroundOscuro,
    onBackground = onBackgroundOscuro,
    surface = surfaceOscuro,
    onSurface = onSurfaceOscuro,
    surfaceVariant = surfaceVariantOscuro,
    onSurfaceVariant = onSurfaceVariantOscuro,
    outline = outlineOscuro,
    outlineVariant = outlineVariantOscuro,
    scrim = scrimOscuro,
    inverseSurface = inverseSurfaceOscuro,
    inverseOnSurface = inverseOnSurfaceOscuro,
    inversePrimary = inversePrimaryOscuro,
    surfaceDim = surfaceDimOscuro,
    surfaceBright = surfaceBrightOscuro,
    surfaceContainerLowest = surfaceContainerLowestOscuro,
    surfaceContainerLow = surfaceContainerLowOscuro,
    surfaceContainer = surfaceContainerOscuro,
    surfaceContainerHigh = surfaceContainerHighOscuro,
    surfaceContainerHighest = surfaceContainerHighestOscuro,
    surfaceTint = surfaceTintOscuro,
)

